micronaut:
  application:
    name: fcli
    
jackson:
  # Micronaut Jackson introspection behavior is too different from reflection-based access, causing issues in native images,
  # so we disable this module altogether and instead rely on @ReflectiveAccess annotations
  bean-introspection-module: false 
  serialization:
    writeDatesAsTimestamps: false
